package com.embehome.embehome.irb


/** com.tronx.tt_things_app.irb
 *   TT_THINGS_APP
 *
 *   Created by Aasim Kutub on 01-06-2020.
 *   Copyright © 2019 tronX things. All rights reserved.
 **/


enum class AcRemoteInfo {
    MODE,   AUTO,   FAN,    RESET,  CLEAN,  SWING_H,    SWING_V,  POWER,  UP, DOWN
}


enum class TVRemoteInfo {
    KEY_POWER,    KEY_INPUT,    KEY_LIST,    KEY_SHARE,
    KEY_AUTO,    KEY_GUIDE,    KEY_MENU,    KEY_EXIT,
    KEY_HOME,    KEY_MUTE,

    KEY_VOLUME_UP,    KEY_VOLUME_DOWN,    KEY_CHANNEL_UP,    KEY_CHANNEL_DOWN,

    KEY_PLAY,    KEY_INFO,    KEY_PAUSE,    KEY_SETTING,
    KEY_STOP,    KEY_WEB,

    KEY_UP,    KEY_DOWN,    KEY_OK,    KEY_RIGHT,
    KEY_LEFT,

    KEY_BACK,    KEY_REFRESH,

    KEY_RED,    KEY_GREEN,    KEY_YELLOW,    KEY_BLUE,

    KEY_1,    KEY_2,    KEY_3,    KEY_4,
    KEY_5,    KEY_6,    KEY_7,    KEY_8,
    KEY_9,    KEY_0,    KEY_REMOVE,    KEY_CC
}

enum class AudioSystemRemoteInfo {
    KEY_POWER,  KEY_TV,  KEY_VOLUME_DOWN,    KEY_VOLUME_UP,    KEY_MUTE,     KEY_DVR,
    KEY_UP,     KEY_DOWN,   KEY_LEFT,   KEY_RIGHT,      KEY_OK,     KEY_MENU,   KEY_REFRESH,    KEY_EXIT,
    KEY_FORWARD,    KEY_PLAY,   KEY_PAUSE,  KEY_STOP,   KEY_REWIND,     KEY_NEXT,   KEY_PREV,    KEY_RADIO,
    KEY_USB, KEY_AUX,   KEY_BACK,   KEY_FAVORITE, KEY_PLAYLIST,     KEY_INFO,   KEY_SHUFFLE,    KEY_AUTO, KEY_REPLAY
}

enum class FanRemoteInfo {
    KEY_LIGHT_POWER,    KEY_POWER,  KEY_LIGHT_UP,   KEY_LIGHT_DOWN,     KEY_SPEED_UP,   KEY_SPEED_DOWN,
    KEY_SLEEP_2H,   KEY_SLEEP_4H,   KEY_SLEEP_6H,      KEY_SLEEP_FAN
}

enum class ProjectorRemoteInfo {
    KEY_POWER,    KEY_INPUT,    KEY_VOLUME_UP,    KEY_VOLUME_DOWN,      KEY_UP,     KEY_DOWN,   KEY_LEFT,   KEY_RIGHT,      KEY_OK,
    KEY_MENU,   KEY_REFRESH,    KEY_SCREENOFF,      KEY_SCREENSIZE,     KEY_AUTOFOCUS,      KEY_KEYSTORE,
    KEY_FREEZE,     KEY_RESET,  KEY_PLAY,   KEY_PAUSE,  KEY_STOP,   KEY_NEXT,   KEY_PREV,   KEY_VGA1,   KEY_VGA2,   KEY_ESC,
    KEY_FORWARD,    KEY_REWIND,     KEY_BACK,   KEY_SEARCH,     KEY_INFO,   KEY_LIST,   KEY_RECORD,     KEY_FOCUS_IN,   KEY_FOCUS_OUT
}

enum class SetupBoxRemoteInfo {
    KEY_POWER,    KEY_INPUT,    KEY_STABILIZER,    KEY_RECORD,
    KEY_AUTO,    KEY_GUIDE,    KEY_MENU,    KEY_EXIT,
    KEY_INBOX,    KEY_MUTE,

    KEY_VOLUME_UP,    KEY_VOLUME_DOWN,    KEY_CHANNEL_UP,    KEY_CHANNEL_DOWN,

    KEY_PLAY,    KEY_INFO,    KEY_PAUSE,    KEY_SETTING,
    KEY_STOP,    KEY_FAVOURITE,

    KEY_UP,    KEY_DOWN,    KEY_OK,    KEY_RIGHT,
    KEY_LEFT,

    KEY_BACK,

    KEY_RED,    KEY_GREEN,    KEY_YELLOW,    KEY_BLUE,

    KEY_1,    KEY_2,    KEY_3,    KEY_4,
    KEY_5,    KEY_6,    KEY_7,    KEY_8,
    KEY_9,    KEY_0,    KEY_REMOVE,    KEY_HELP
}

enum class DVDRemoteInfo {
    KEY_POWER,    KEY_INPUT,      KEY_EJECT,    KEY_MENU,
    KEY_PROGRAM,    KEY_MUTE,   KEY_OSD,

    KEY_VOLUME_UP,    KEY_VOLUME_DOWN,    KEY_CHANNEL_UP,    KEY_CHANNEL_DOWN,

    KEY_FORWARD,    KEY_PLAY,   KEY_PAUSE,  KEY_STOP,   KEY_REWIND,     KEY_NEXT,   KEY_PREV,
    KEY_INFO,       KEY_SETTING,

    KEY_UP,    KEY_DOWN,       KEY_RIGHT,    KEY_LEFT, KEY_OK,

    KEY_BACK,    KEY_MIC,

    KEY_NTSC_PAL,    KEY_SHUFFLE,

    KEY_1,    KEY_2,    KEY_3,    KEY_4,
    KEY_5,    KEY_6,    KEY_7,    KEY_8,
    KEY_9,    KEY_0,    KEY_REMOVE,    KEY_SEARCH
}

enum class TableFanRemoteInfo {
    KEY_POWER,  KEY_LEVEL_1,    KEY_LEVEL_2,    KEY_LEVEL_3,    KEY_LEVEL_4,    KEY_SWING,  KEY_TIMER
}

enum class CeilingFanRemoteInfo {
    KEY_POWER,  KEY_LEVEL_1,    KEY_LEVEL_2,    KEY_LEVEL_3,    KEY_LEVEL_4,    KEY_LIGHT,  KEY_TIMER
}

enum class CoolerRemoteInfo {
    KEY_POWER,  KEY_LEVEL_1,    KEY_LEVEL_2,    KEY_LEVEL_3,       KEY_SWING,  KEY_TIMER,  KEY_COOL
}

enum class GeyserRemoteInfo {
    KEY_POWER, KEY_AUTO,    KEY_MODE,   KEY_SET,    KEY_TIMER,  KEY_INCREASE, KEY_DECREASE
}

enum class AirPurifierRemoteInfo {
    KEY_POWER,  KEY_AUTO,   KEY_FAN_LOW,    KEY_FAN_MEDIUM,     KEY_FAN_HIGH,
    KEY_TIMER,  KEY_INCREASE, KEY_DECREASE,     KEY_SLEEP,  KEY_FAV,    KEY_WARM
}


enum class RemoteButtons {
    KEY_POWER,    KEY_INPUT,    KEY_LIST,    KEY_SHARE,
    KEY_AUTO,    KEY_GUIDE,    KEY_MENU,    KEY_EXIT,
    KEY_HOME,    KEY_MUTE,

    KEY_VOLUME_UP,    KEY_VOLUME_DOWN,    KEY_CHANNEL_UP,    KEY_CHANNEL_DOWN,

    KEY_PLAY,    KEY_INFO,    KEY_PAUSE,    KEY_SETTING,
    KEY_STOP,    KEY_WEB,

    KEY_UP,    KEY_DOWN,    KEY_OK,    KEY_RIGHT,
    KEY_LEFT,

    KEY_BACK,    KEY_REFRESH, KEY_REPEAT, KEY_MESSAGE,

    KEY_RED,    KEY_GREEN,    KEY_YELLOW,    KEY_BLUE,

    KEY_1,    KEY_2,    KEY_3,    KEY_4,
    KEY_5,    KEY_6,    KEY_7,    KEY_8,
    KEY_9,    KEY_0,    KEY_REMOVE,    KEY_CC,

      KEY_TV,       KEY_DVR,

    KEY_FORWARD,       KEY_REWIND,     KEY_NEXT,   KEY_PREV,    KEY_RADIO,
    KEY_USB, KEY_AUX,      KEY_FAVORITE, KEY_PLAYLIST,        KEY_SHUFFLE,     KEY_REPLAY,

    KEY_LIGHT_POWER,      KEY_LIGHT_UP,   KEY_LIGHT_DOWN,     KEY_SPEED_UP,   KEY_SPEED_DOWN,
    KEY_SLEEP_2H,   KEY_SLEEP_4H,   KEY_SLEEP_6H,      KEY_SLEEP_FAN,


        KEY_SCREENOFF,      KEY_SCREENSIZE,     KEY_AUTOFOCUS,      KEY_KEYSTORE,
    KEY_FREEZE,     KEY_RESET,     KEY_VGA1,   KEY_VGA2,   KEY_ESC,
       KEY_SEARCH,        KEY_RECORD,     KEY_FOCUS_IN,   KEY_FOCUS_OUT,

        KEY_STABILIZER,
    KEY_INBOX,

        KEY_FAVOURITE,

        KEY_HELP,


         KEY_EJECT,
    KEY_PROGRAM,       KEY_OSD,     KEY_QUICK,          KEY_CLEAN,   KEY_FULL_SCREEN,   KEY_SOURCE,   KEY_ENTER,

    KEY_VIDEO,      KEY_CONTROLLER_UP,  KEY_CONTROLLER_DOWN,        KEY_PROGRAMMER_UP,      KEY_PROGRAMMER_DOWN,





       KEY_MIC,

    KEY_NTSC_PAL,

      KEY_LEVEL_1,    KEY_LEVEL_2,    KEY_LEVEL_3,    KEY_LEVEL_4,    KEY_SWING,  KEY_TIMER,


        KEY_LIGHT,

      KEY_COOL,

        KEY_MODE,   KEY_SET,      KEY_INCREASE, KEY_DECREASE,


       KEY_FAN_LOW,    KEY_FAN_MEDIUM,     KEY_FAN_HIGH,
        KEY_SLEEP,      KEY_WARM , KEY_LOW,


    KEY_POWER_ON,   KEY_POWER_OFF,
    KEY_SWING_ON,  KEY_SWING_OFF,
    KEY_VERTICAL_SWING_UP, KEY_VERTICAL_SWING_MID,  KEY_VERTICAL_SWING_DOWN,
    KEY_FAN_OFF,
    KEY_MODE_AUTO,  KEY_MODE_COOL,  KEY_MODE_DRY,   KEY_MODE_HEAT,
    KEY_AUTO_17, KEY_AUTO_18, KEY_AUTO_19, KEY_AUTO_20, KEY_AUTO_21, KEY_AUTO_22, KEY_AUTO_23, KEY_AUTO_24, KEY_AUTO_25, KEY_AUTO_26, KEY_AUTO_27, KEY_AUTO_28, KEY_AUTO_29, KEY_AUTO_30,
    KEY_COOL_17, KEY_COOL_18, KEY_COOL_19, KEY_COOL_20, KEY_COOL_21, KEY_COOL_22, KEY_COOL_23, KEY_COOL_24, KEY_COOL_25, KEY_COOL_26, KEY_COOL_27, KEY_COOL_28, KEY_COOL_29, KEY_COOL_30,
    KEY_DRY_17, KEY_DRY_18, KEY_DRY_19, KEY_DRY_20, KEY_DRY_21, KEY_DRY_22, KEY_DRY_23, KEY_DRY_24, KEY_DRY_25, KEY_DRY_26, KEY_DRY_27, KEY_DRY_28, KEY_DRY_29, KEY_DRY_30,
    KEY_HEAT_17, KEY_HEAT_18, KEY_HEAT_19, KEY_HEAT_20, KEY_HEAT_21, KEY_HEAT_22, KEY_HEAT_23, KEY_HEAT_24, KEY_HEAT_25, KEY_HEAT_26, KEY_HEAT_27, KEY_HEAT_28, KEY_HEAT_29, KEY_HEAT_30

}
